#!/usr/bin/env node

'use strict';

const express = require('express');
const app = express();
const bodyParser = require('body-parser');

app.use(bodyParser.json());

app.post('/github', function (req, res) {
	console.log(req.body);
	res.sendStatus(200);
});

app.listen(8001);