#!/usr/bin/env node

'use strict';

const express = require('express');
const bodyParser = require('body-parser');
const crypto = require('crypto');

const app = express();

app.use(bodyParser.json({
	verify: function (req, res, buf, encoding) {
		let hash = crypto.createHash('sha1');
		hash.update(buf);
		console.log("hash", hash.digest('hex'));
	}
}));

app.post('/github', function (req, res) {
	var headers = req.headers;
	let shasum = crypto.createHash('sha1');

	// Basic sanity checks
	if (!req.body || req.headers['x-github-event'] !== 'push') {
		return res.sendStatus(400);
	}

	res.sendStatus(200);
});

app.listen(8001);